### ISSUE TITLE
App is not running

### ISSUE THREAD

**Issue by xubairp** [3Alan/DocsMind#15]
Hello,

 I followed the steps mentioned under the LOCAL DEVELOPMENT. all steps were executed without any issue. however, when i try to access the app at http://localhost:5173/  i get the 404 error.

![image](https://user-images.githubusercontent.com/128311411/236686825-7efb843f-893a-4551-b51d-3aaee56bcd53.png)

![image](https://user-images.githubusercontent.com/128311411/236687097-91359ca9-33e9-4409-96f6-6d3af44fbef9.png)

and checking the logs, its empty.

--------------------

Then it tried to access and test the flask service at http://localhost:8080/ and i get : 
`
{"message":"404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."}`

I find this in the log :
```

werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2023-05-07 23:25:02 ERROR: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\x\DocsMind-1\server\.venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\DocsMind-1\server\.venv\Lib\site-packages\flask\app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\x\DocsMind-1\server\.venv\Lib\site-packages\flask\app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\DocsMind-1\server\.venv\Lib\site-packages\flask\ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\DocsMind-1\server\.venv\Lib\site-packages\werkzeug\routing\map.py", line 652, in match
    raise NotFound() from None

```

**Comment by 3Alan** [comment]
Returning a 404 error after accessing http://localhost:8080 indicates that your backend service is running successfully, so you don't need to worry about it. As for the issue of being unable to access 5173, you can try accessing http://127.0.0.1:5173/ or  changing to another unused port.
```
yarn dev --port 3000
```
If you still can't solve it, you need to resolve it on your own. This is a Vite issue.
