### ISSUE TITLE
[Bug]: 上传pdf文件超过一次分页就死循环

### ISSUE THREAD

**Issue by wh1138220** [3Alan/DocsMind#30]
### Describe the bug

本来的问题是md上传很快，pdf上传永远卡死，也没有报错日志出现，
代码在 pdf_loader.py的 text_chunks = sentence_splitter.split_text(text) 这一行
经过debug后，调整了 llama_index/langchain_helpers/text_splitter.py 的 new_splits.pop(0) 这一行，pdf可以上传成功，但是只是上传成功而已，功能好像是欠缺的，截图如下，请参考
如果不调整，会一直死循环在 while len(new_splits) > 0:  的循环里

<img width="470" alt="7cda41c4187fc813b179b6e985f4f5e" src="https://github.com/3Alan/DocsMind/assets/6500269/64f5fe84-2a18-4a53-b059-9701e0a8d94a">

### Relevant log output

```shell
2023-06-20 06:16:38 ERROR: RetryError[<Future at 0x7f6013630280 state=finished raised RateLimitError>]
Traceback (most recent call last):
  File "/root/local/DocsMind/server/.venv/lib/python3.9/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/root/local/DocsMind/server/.venv/lib/python3.9/site-packages/llama_index/embeddings/openai.py", line 106, in get_embedding
    return openai.Embedding.create(input=[text], engine=engine)["data"][0]["embedding"]
  File "/root/local/DocsMind/server/.venv/lib/python3.9/site-packages/openai/api_resources/embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "/root/local/DocsMind/server/.venv/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/root/local/DocsMind/server/.venv/lib/python3.9/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/root/local/DocsMind/server/.venv/lib/python3.9/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/root/local/DocsMind/server/.venv/lib/python3.9/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error and would like to appeal, please contact us through our help center at help.openai.com.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/local/DocsMind/server/.venv/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/local/DocsMind/server/.venv/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/root/local/DocsMind/server/app.py", line 148, in query_index
    res = index.query(query_text, streaming=True)
  File "/root/local/DocsMind/server/.venv/lib/python3.9/site-packages/llama_index/indices/base.py", line 260, in query
    return query_runner.query(query_str)
  File "/root/local/DocsMind/server/.venv/lib/python3.9/site-packages/llama_index/indices/query/query_runner.py", line 349, in query
    return query_combiner.run(query_bundle, level)
  File "/root/local/DocsMind/server/.venv/lib/python3.9/site-packages/llama_index/indices/query/query_combiner/base.py", line 68, in run
    return self._query_runner.query_transformed(
  File "/root/local/DocsMind/server/.venv/lib/python3.9/site-packages/llama_index/indices/query/query_runner.py", line 209, in query_transformed
    return query_obj.query(query_bundle)
  File "/root/local/DocsMind/server/.venv/lib/python3.9/site-packages/llama_index/token_counter/token_counter.py", line 78, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
  File "/root/local/DocsMind/server/.venv/lib/python3.9/site-packages/llama_index/indices/query/base.py", line 206, in query
    nodes = self.retrieve(query_bundle)
  File "/root/local/DocsMind/server/.venv/lib/python3.9/site-packages/llama_index/indices/query/base.py", line 166, in retrieve
    nodes = self._retrieve(query_bundle, similarity_tracker=similarity_tracker)
  File "/root/local/DocsMind/server/.venv/lib/python3.9/site-packages/llama_index/indices/vector_store/base_query.py", line 62, in _retrieve
    self._service_context.embed_model.get_agg_embedding_from_queries(
  File "/root/local/DocsMind/server/.venv/lib/python3.9/site-packages/llama_index/embeddings/base.py", line 83, in get_agg_embedding_from_queries
    query_embeddings = [self.get_query_embedding(query) for query in queries]
  File "/root/local/DocsMind/server/.venv/lib/python3.9/site-packages/llama_index/embeddings/base.py", line 83, in <listcomp>
    query_embeddings = [self.get_query_embedding(query) for query in queries]
  File "/root/local/DocsMind/server/.venv/lib/python3.9/site-packages/llama_index/embeddings/base.py", line 72, in get_query_embedding
    query_embedding = self._get_query_embedding(query)
  File "/root/local/DocsMind/server/.venv/lib/python3.9/site-packages/llama_index/embeddings/openai.py", line 223, in _get_query_embedding
    return get_embedding(query, engine=engine)
  File "/root/local/DocsMind/server/.venv/lib/python3.9/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/root/local/DocsMind/server/.venv/lib/python3.9/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/root/local/DocsMind/server/.venv/lib/python3.9/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f6013630280 state=finished raised RateLimitError>]
```

### Validations

- [X] Already read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by 3Alan** [comment]
> openai.error.RateLimitError: Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error and would like to appeal, please contact us through our help center at help.openai.com.

从log中看出是你的openai账号问题，看上去被ban了

**Comment by wh1138220** [comment]
> > openai.error.RateLimitError: Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error and would like to appeal, please contact us through our help center at help.openai.com.
> 
> 从log中看出是你的openai账号问题，看上去被ban了

虽然确实也切换过已经过期的key使用过，但确实并没有被ban，apikey和账号都正常可用，如果没有其他人有相同反馈，可忽略这个问题
