### ISSUE TITLE
[Bug]: Unable to upload file.

### ISSUE THREAD

**Issue by adnaniz** [3Alan/DocsMind#32]
### Describe the bug

Unable to upload file.
Looks like front end isn't communicating with back. pls help.

tried other ways as per other issues but unable to fix it.

### Relevant log output

```shell
129.154.45.16/:1 Unchecked runtime.lastError: The message port closed before a response was received.
contentScript.bundle.js:533 Content script works!
contentScript.bundle.js:533 Must reload extension for modifications to take effect.
script.js:1 Uncaught SyntaxError: Unexpected token '<' (at script.js:1:1)
index-33b23838.js:337     GET http://localhost:8080/api/file-list net::ERR_CONNECTION_REFUSED
(anonymous) @ index-33b23838.js:337
xhr @ index-33b23838.js:337
dispatchRequest @ index-33b23838.js:337
request @ index-33b23838.js:337
(anonymous) @ index-33b23838.js:335
et @ index-33b23838.js:352
(anonymous) @ index-33b23838.js:352
Rj @ index-33b23838.js:40
Ik @ index-33b23838.js:40
Fk @ index-33b23838.js:40
jg @ index-33b23838.js:38
Xk @ index-33b23838.js:40
Qk @ index-33b23838.js:40
Hk @ index-33b23838.js:40
xt @ index-33b23838.js:25
Pt @ index-33b23838.js:25
index-33b23838.js:337 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'data')
    at index-33b23838.js:337:16089
    at async et (index-33b23838.js:352:9019)
```

### Validations

- [X] Already read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Arthur-Llevelys** [comment]
I have the same error when I try to upload a file from a website : http://docsmind.example.com

But I haven't error when I use it by :  http://localhost:8080 ...

```
Uncaught SyntaxError: Unexpected token '<' (at script.js:1:1)
index-33b23838.js:337 
             
       GET http://localhost:8080/api/file-list net::ERR_CONNECTION_REFUSED
(anonymous) @ index-33b23838.js:337
xhr @ index-33b23838.js:337
dispatchRequest @ index-33b23838.js:337
request @ index-33b23838.js:337
(anonymous) @ index-33b23838.js:335
et @ index-33b23838.js:352
(anonymous) @ index-33b23838.js:352
Rj @ index-33b23838.js:40
Ik @ index-33b23838.js:40
Fk @ index-33b23838.js:40
jg @ index-33b23838.js:38
Xk @ index-33b23838.js:40
Qk @ index-33b23838.js:40
Hk @ index-33b23838.js:40
xt @ index-33b23838.js:25
Pt @ index-33b23838.js:25
index-33b23838.js:337 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'data')
    at index-33b23838.js:337:16089
    at async et (index-33b23838.js:352:9019)
(anonymous) @ index-33b23838.js:337
await in (anonymous) (async)
(anonymous) @ index-33b23838.js:352
Rj @ index-33b23838.js:40
Ik @ index-33b23838.js:40
Fk @ index-33b23838.js:40
jg @ index-33b23838.js:38
Xk @ index-33b23838.js:40
Qk @ index-33b23838.js:40
Hk @ index-33b23838.js:40
xt @ index-33b23838.js:25
Pt @ index-33b23838.js:25
```

my Virtualhost apache configuration is : 

```
<VirtualHost *:34080>
ServerName docsmind.example.com
ProxyPreserveHost On
ProxyPass / http://127.0.0.1:8081/
ProxyPassReverse / http://127.0.0.1:8081/
RewriteRule ^/(.*)?$ http://127.0.0.1:8081/$1 [P,L]
  <Proxy *>
    Allow from all
  </Proxy>
        <Directory /var/www/html/ai/DocsMind/data/>
            Require all granted
            Options FollowSymlinks MultiViews
            AllowOverride All
        Satisfy Any
       </Directory>
ProxyPass / http://localhost:8080/api/file-list
ProxyPassReverse / http://localhost:8080/api/file-list
ErrorLog ${APACHE_LOG_DIR}/docsmind.error.log
CustomLog ${APACHE_LOG_DIR}/docsmind.access.log combined
</VirtualHost>
```
