### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by beralc** [3Alan/DocsMind#5]
I'm getting this error: 
{"message":"404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."}

<img width="765" alt="image" src="https://user-images.githubusercontent.com/10000606/233805255-2d86c579-0217-45ed-9a25-e323caec5600.png">

What could the issue be?

**Comment by 3Alan** [comment]
As the information you provided is limited, I cannot analyze the cause of the error. Please provide the log located at `api-src/app.log` and the client error (browser console) so that I can better understand the issue.

**Comment by beralc** [comment]
Hi. Thanks for getting back so quickly. These are the contents of the file: 
2023-04-22 22:16:01 ERROR: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2023-04-22 22:16:01 ERROR: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2023-04-22 22:16:14 ERROR: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2023-04-22 22:16:14 ERROR: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2023-04-22 22:16:15 ERROR: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2023-04-22 22:16:15 ERROR: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2023-04-22 22:20:35 ERROR: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2023-04-22 22:20:35 ERROR: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2023-04-22 22:20:39 ERROR: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2023-04-22 22:23:30 ERROR: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2023-04-22 22:23:30 ERROR: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2023-04-22 22:25:02 ERROR: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2023-04-22 22:25:02 ERROR: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2023-04-22 22:28:19 ERROR: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2023-04-22 22:28:20 ERROR: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2023-04-22 22:34:00 ERROR: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2023-04-22 22:34:01 ERROR: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2023-04-22 22:34:10 ERROR: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bernardomorales/this one is it/chat-markdown/api-src/.venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by 3Alan** [comment]
What is the URL you requested that resulted in a 404 error? Have you followed the steps in the README to start both the frontend and backend programs? Can you provide a screen recording?

**Comment by 3Alan** [comment]
Access http://127.0.0.1:5173/ instead of http://127.0.0.1:5000/. 5000 is the entrance of the backend service.

**Comment by beralc** [comment]
I get the same 404 error
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/10000606/234005784-a7926e99-6b26-48d9-9017-1489b037faba.png">

**Comment by 3Alan** [comment]
I'm not sure why your backend service has so many ports like 5173 and 5000. It didn't seem like a problem with the project at that time. Maybe you can try killing all the ports and restarting to see if it helps.

**Comment by beralc** [comment]
I killed all the ports and used port 5000, still getting the 404
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/10000606/234022857-43835603-e3de-49a7-8f95-b6dcca891fec.png">

**Comment by beralc** [comment]
Another issue, which may be causing this problem, is that I haven't put a vite_services_url in the env file. But I don't know where to get it from. Could that be causing the issue?

**Comment by beralc** [comment]
Thanks for your help. I still don't get how I should access the UI. I tried to access :5173 but I get a "site can't be reached" error. I don't understand what I'm doing wrong.

**Comment by 3Alan** [comment]
Did you execute "yarn dev"?

**Comment by beralc** [comment]
I did, but it doesn't let me upload pdfs.

**Comment by 3Alan** [comment]
Can you see the default markdown and ask questions?

**Comment by beralc** [comment]
No. it looks like this: 
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/10000606/234249837-909c2f2b-bb0b-4b2e-a8e0-f855c58b6eda.png">

**Comment by beralc** [comment]
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/10000606/234250863-94c8c785-3ab6-438f-a3fa-436bc781302f.png">

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/10000606/234250785-114a8e63-82b4-4c13-b431-4b5f1f17ded8.png">

**Comment by 3Alan** [comment]
visit page in an Incognito window and view console errors

**Comment by beralc** [comment]
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/10000606/234259148-5f347985-6242-451e-a887-6c276802b920.png">

<img width="676" alt="image" src="https://user-images.githubusercontent.com/10000606/234259201-d7f09077-25fc-4f29-a423-8a993246fdfe.png">

**Comment by beralc** [comment]
I restarted everything, and now I can see the default document, and chat with it. But I can't upload my own
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/10000606/234259845-e1ee7808-4e64-4650-8ddf-6713886236cb.png">

**Comment by 3Alan** [comment]
Please provide the error message that occurred when you uploaded.

**Comment by beralc** [comment]
There is no error message. Nothing happens when i drag a file, and when it won't let me select a file when i click on "Click or drag file to this area to upload" I'm attaching a screenshot of the console. 
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/10000606/234261874-8831e3af-4588-4570-98aa-4735ffe5ae5d.png">

**Comment by 3Alan** [comment]
Is the file you uploaded a markdown file? Currently, only .md files are supported

**Comment by beralc** [comment]
This happens when i try to upload a text I converted to MD 
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/10000606/234271207-6a46a073-76c1-472f-8231-ac41f26b39f7.png">

And this when I upload some other md files. 
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/10000606/234271388-12d0ce36-8731-47d0-b344-7a8ff7724ab7.png">

**Comment by 3Alan** [comment]
The first error is a known bug caused by the lack of a title in your file. Please try adding a title to your .md file as shown below:

```
# your md title
```
I will fix the second error as soon as possible.

**Comment by beralc** [comment]
Thanks so much for your help. It's greatly appreciated.

**Comment by 3Alan** [comment]
The latest code has fixed the second error. https://github.com/3Alan/chat-markdown/issues/6#issue-1683061337

**Comment by beralc** [comment]
I got the latest code, and I'm getting the other error again: 
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/10000606/234309001-3f7729d1-703d-4ef6-933a-0f7d56c07579.png">

**Comment by 3Alan** [comment]
I don't know why you keep encountering this issue. Perhaps your port 5000 is being used by another application, so you can only try changing it to another port. Use "flask run --reload --port=8080" to run the backend on the new port, and then replace all instances of ":5000" in the code globally with the new port.
